version: '2'
services:
    redis:
        container_name: cache
        image: redis
        expose:
            - 6379    
    app:
        build: ./
        links:
            - redis
        ports:
            - 3001:3000
        environment:
            - REDIS_URL=redis://cache
            - PORT=3000
            - DBHOST=${DBHOST}
            - DBPORT=${DBPORT}
            - DBUSER=${DBUSER}
            - DBPASS=${DBPASS}
            - DBPLAYER=${DBPLAYER}
            